Fix SonarCloud code coverage reporting
We have started seeing an error from SonarCloud when it tries to read our SimpleCov output file.

```bash
INFO: Sensor SimpleCov Sensor for Ruby coverage [ruby]
ERROR: Cannot read coverage report file, expecting standard SimpleCov resultset JSON format: 'coverage/.resultset.json'
java.lang.ClassCastException: org.sonarsource.analyzer.commons.internal.json.simple.JSONObject cannot be cast to org.sonarsource.analyzer.commons.internal.json.simple.JSONArray
	at org.sonarsource.ruby.plugin.SimpleCovSensor.mergeFrameworkCoverages(SimpleCovSensor.java:121)
	at org.sonarsource.ruby.plugin.SimpleCovSensor.mergeFileCoverages(SimpleCovSensor.java:114)
```

We think this may be due to the recent change to use the latest version of SimpleCov to resolve a security issue with the version of JSON it was using (see PR https://github.com/DEFRA/waste-carriers-back-office/pull/807).

This change ensures SonarCloud can read our code coverage again.

Note. This may not be the issue, but its the current working assumption!